// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

const _sweeteditorAssetId = 'package:sweeteditor/lib/sweeteditor.dart';

/// Create a Document and return its handle
/// @param text UTF8 text content
/// @return Document handle
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Char>)>(
  assetId: _sweeteditorAssetId,
)
external int create_document_from_utf8(ffi.Pointer<ffi.Char> text);

/// Create a Document and return its handle
/// @param text UTF16 text content
/// @return Document handle
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Uint16>)>(
  assetId: _sweeteditorAssetId,
)
external int create_document_from_utf16(ffi.Pointer<ffi.Uint16> text);

/// Create a Document and return its handle(created from local file)
/// @param path Local file path
/// @return Document handle
@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Char>)>(
  assetId: _sweeteditorAssetId,
)
external int create_document_from_file(ffi.Pointer<ffi.Char> path);

/// Free Document
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_document(int document_handle);

/// Get Document UTF8 text
/// @return UTF8 text content; caller owns returned buffer and must free it with free_u8_string
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> get_document_utf8(int document_handle);

/// Get Document UTF16 text
/// @return UTF16 text content; caller owns returned buffer and must free it with free_u16_string
@ffi.Native<ffi.Pointer<ffi.Uint16> Function(ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint16> get_document_utf16(int document_handle);

/// Get total line count of Document
/// @return total line count of Document
@ffi.Native<ffi.Size Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int get_document_line_count(int document_handle);

/// Get UTF8 text of a specific Document line
/// @param line Line number
/// @return UTF8 text content of the specified line; caller owns returned buffer and must free it with free_u8_string
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> get_document_line_utf8(
  int document_handle,
  int line,
);

/// Get UTF16 text of a specific Document line
/// @param line Line number
/// @return UTF16 text content of the specified line; caller owns returned buffer and must free it with free_u16_string
@ffi.Native<ffi.Pointer<ffi.Uint16> Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint16> get_document_line_utf16(
  int document_handle,
  int line,
);

/// Create EditorCore and return its handle
/// @param measurer Text measurement callback set
/// @param options_data EditorOptions binary payload encoded by CoreProtocol:
/// f32 touch_slop
/// i64 double_tap_timeout
/// i64 long_press_ms
/// f32 fling_friction
/// f32 fling_min_velocity
/// f32 fling_max_velocity
/// u64 max_undo_stack_size
/// i64 key_chord_timeout_ms
/// bool_u8 reveal_selection_end_on_select_all
/// @param options_size Byte length of options_data
/// @return EditorCore handle
@ffi.Native<
  ffi.IntPtr Function(text_measurer_t, ffi.Pointer<ffi.Uint8>, ffi.Size)
>(assetId: _sweeteditorAssetId)
external int create_editor(
  text_measurer_t measurer,
  ffi.Pointer<ffi.Uint8> options_data,
  int options_size,
);

/// Free EditorCore
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_editor(int editor_handle);

/// Load Document
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.IntPtr, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_document(
  int editor_handle,
  int document_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set editor viewport
/// @param width Editor view width
/// @param height Editor view height
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_viewport(
  int editor_handle,
  int width,
  int height,
  ffi.Pointer<ffi.Size> out_size,
);

/// Notify editor that font metrics have changed (call after font/scale changes)
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_on_font_metrics_changed(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set fold arrow display mode (affects reserved gutter width)
/// @param mode 0=AUTO(auto show when fold regions exist), 1=ALWAYS(always reserve), 2=HIDDEN(always hide)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_fold_arrow_mode(
  int editor_handle,
  int mode,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set auto wrap mode
/// @param mode 0=NONE(no wrap), 1=CHAR_BREAK(character-level wrap), 2=WORD_BREAK(word-level wrap)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_wrap_mode(
  int editor_handle,
  int mode,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set tab size (number of spaces per tab stop)
/// @param tab_size Tab size (default 4, minimum 1)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_tab_size(
  int editor_handle,
  int tab_size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set editor scale factor
/// @param scale Scale factor (1.0 = 100%)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Float, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_scale(
  int editor_handle,
  double scale,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set line spacing parameters (formula: line_height = font_height * mult + add)
/// @param add Extra line spacing in pixels (default 0)
/// @param mult Line spacing multiplier (default 1.0)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_spacing(
  int editor_handle,
  double add,
  double mult,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set extra horizontal padding between gutter split and text content start
/// @param padding Padding in pixels (clamped to >= 0)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Float, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_content_start_padding(
  int editor_handle,
  double padding,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set whether to render gutter split line
/// @param show 0=hide, non-zero=show
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_show_split_line(
  int editor_handle,
  int show,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set current line render mode
/// @param mode 0=BACKGROUND(fill), 1=BORDER(stroke), 2=NONE(disabled)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_current_line_render_mode(
  int editor_handle,
  int mode,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set whitespace marker rendering mode
/// @param mode 0=NONE, 1=BOUNDARY, 2=SELECTION, 3=TRAILING, 4=ALL
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_render_whitespace(
  int editor_handle,
  int mode,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set whether line-ending markers should be rendered
/// @param enabled 0=hide, non-zero=show
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_render_line_breaks(
  int editor_handle,
  int enabled,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set whether gutter stays fixed during horizontal scroll
/// @param sticky 0=gutter scrolls with content (mobile style), non-zero=gutter fixed (desktop style)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_gutter_sticky(
  int editor_handle,
  int sticky,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set whether gutter area is visible
/// @param visible 0=hide entire gutter, non-zero=show gutter
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_gutter_visible(
  int editor_handle,
  int visible,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set selection handle hit-test configuration.
/// @param data HandleConfig binary payload encoded by CoreProtocol:
/// HandleHitArea start_hit_area
/// HandleHitArea end_hit_area
/// HandleHitArea is f32 left, f32 top, f32 right, f32 bottom
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_handle_config(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set scrollbar full configuration (geometry + behavior).
/// @param data ScrollbarConfig binary payload encoded by CoreProtocol:
/// f32 thickness
/// f32 min_thumb
/// f32 thumb_hit_padding
/// enum_i32 mode
/// bool_u8 thumb_draggable
/// enum_i32 track_tap_mode
/// u16 fade_delay_ms
/// u16 fade_duration_ms
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_scrollbar_config(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set editor colors resolved by core when building visual runs.
/// @param data EditorRenderColors binary payload encoded by CoreProtocol:
/// i32 text_foreground
/// i32 link_foreground
/// i32 active_link_foreground
/// i32 codelens_foreground
/// i32 active_codelens_foreground
/// @param size payload byte length
/// @param out_size Output: payload byte length (bytes, excluding extra '\0' terminator)
/// @return EditorActionResult binary payload encoded by CoreProtocol
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_editor_render_colors(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set range-effect styles resolved by core when building the render model.
/// @param data EditorRangeEffectStyles binary payload encoded by CoreProtocol
/// @param size payload byte length
/// @param out_size Output: payload byte length (bytes, excluding extra '\0' terminator)
/// @return EditorActionResult binary payload encoded by CoreProtocol
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_editor_range_effect_styles(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Build render model for one editor frame
/// @param out_size Output: payload byte length (bytes, excluding extra '\0' terminator)
/// @return EditorRenderModel binary payload encoded by CoreProtocol. Caller owns returned buffer and must free it with free_binary_data.
/// Wire layout:
/// f32 split_x
/// bool_i32 split_line_visible
/// f32 scroll_x
/// f32 scroll_y
/// Size viewport_size
/// PointF current_line
/// enum_i32 current_line_render_mode
/// List<VisualLine> lines
/// Cursor cursor
/// List<RangeEffectRenderItem> range_effects
/// SelectionHandle selection_start_handle
/// SelectionHandle selection_end_handle
/// List<GuideSegment> guide_segments
/// u32 max_gutter_icons
/// List<GutterIconRenderItem> gutter_icons
/// List<FoldMarkerRenderItem> fold_markers
/// ScrollbarModel vertical_scrollbar
/// ScrollbarModel horizontal_scrollbar
/// bool_i32 gutter_sticky
/// bool_i32 gutter_visible
/// enum_i32 pointer_cursor_type
/// VisualLine is i32 logical_line, i32 wrap_index, PointF line_number_position, List<VisualRun> runs, enum_i32 kind, bool_i32 owns_gutter_semantics, enum_i32 fold_state
/// VisualRun is enum_i32 type, f32 x, f32 y, U8String text, TextStyle style, i32 icon_id, i32 color_value, f32 width, f32 padding, f32 margin, bool_i32 active
/// TextStyle is i32 color, i32 background_color, i32 font_style
/// Cursor is TextPosition text_position, PointF position, f32 height, bool_i32 visible, bool_i32 show_dragger
/// Rect is PointF origin, f32 width, f32 height
/// SelectionHandle is PointF position, f32 height, bool_i32 visible
/// RangeEffectRenderItem is Rect rect, enum_i32 kind, RangeEffectStyle style
/// RangeEffectStyle is i32 foreground_color, i32 background_color, i32 border_color, i32 underline_color, enum_i32 underline_style
/// GuideSegment is enum_i32 direction, enum_i32 type, enum_i32 style, PointF start, PointF end, bool_i32 arrow_end
/// GutterIconRenderItem is i32 logical_line, i32 icon_id, Rect rect
/// FoldMarkerRenderItem is i32 logical_line, enum_i32 fold_state, Rect rect
/// ScrollbarModel is bool_i32 visible, f32 alpha, bool_i32 thumb_active, Rect track, Rect thumb
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_build_render_model(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get editor layout metrics
/// @param out_size Output: payload byte length (bytes, excluding extra '\0' terminator)
/// @return LayoutMetrics binary payload encoded by CoreProtocol. Caller owns returned buffer and must free it with free_binary_data.
/// Wire layout:
/// f32 font_height
/// f32 font_ascent
/// f32 line_spacing_add
/// f32 line_spacing_mult
/// f32 line_number_margin
/// f32 line_number_width
/// f32 content_start_padding
/// u32 max_gutter_icons
/// f32 inlay_hint_padding
/// f32 inlay_hint_margin
/// enum_i32 fold_arrow_mode
/// bool_i32 has_fold_regions
/// bool_i32 gutter_sticky
/// bool_i32 gutter_visible
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_get_layout_metrics(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// EditorActionResult binary payloads are encoded by CoreProtocol.
/// Wire layout:
/// bool_i32 handled
/// bool_i32 needs_redraw
/// enum_i32 source
/// enum_i32 text_change_kind
/// bool_i32 cursor_changed
/// bool_i32 selection_changed
/// bool_i32 scroll_changed
/// bool_i32 scale_changed
/// bool_i32 pointer_cursor_changed
/// bool_i32 composition_changed
/// bool_i32 decoration_changed
/// u32 animation_flags
/// u32 next_animation_delay_ms
/// u32 interaction_flags
/// List<TextChange> text_changes
/// TextPosition cursor_before
/// TextPosition cursor_after
/// bool_i32 has_selection_before
/// bool_i32 has_selection_after
/// TextRange selection_before
/// TextRange selection_after
/// f32 scroll_x_before
/// f32 scroll_y_before
/// f32 scroll_x_after
/// f32 scroll_y_after
/// f32 scale_before
/// f32 scale_after
/// enum_i32 pointer_cursor_before
/// enum_i32 pointer_cursor_after
/// enum_i32 ime_host_action
/// ImeState ime_state
/// enum_i32 gesture_type
/// enum_i32 gesture_event_type
/// PointF tap_point
/// HitTarget hit_target
/// enum_i32 modifiers
/// enum_i32 command
/// animation_flags is a bit set: 1=EDGE_SCROLL, 2=FLING, 4=TRANSIENT_SCROLLBAR
/// interaction_flags is a bit set: 1=PRIMARY_POINTER, 2=SELECTION_DRAG, 4=VIEWPORT_GESTURE
/// when animation_flags is nonzero, next_animation_delay_ms=0 requests the next display frame
/// and a positive value requests editor_tick_animations after that delay
/// TextChange is TextRange range followed by U8String new_text
/// ImeState is enum_i32 result_code, u64 session_id, u64 state_revision, ImeSelection selection, ImeOffsetRange composition_range
/// HitTarget is enum_i32 type, i32 line, i32 column, i32 icon_id, i32 color_value
/// This is the only result payload for core state-changing APIs. Platforms should use needs_redraw from this payload
/// to decide whether to flush editor state and schedule repaint.
///
/// Handle gesture event.
/// @param data GestureEvent binary payload encoded by CoreProtocol:
/// enum_i32 type
/// List<PointF> points
/// i32 modifiers
/// f32 wheel_delta_x
/// f32 wheel_delta_y
/// f32 direct_scale
/// PointF is f32 x followed by f32 y
/// @param size payload byte length
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_handle_gesture_event(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Recompute pointer presentation for the last observed mouse position after modifier keys change.
/// @param modifiers Modifier key flags(SHIFT=1, CTRL=2, ALT=4, META=8)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Uint8, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_update_pointer_modifiers(
  int editor_handle,
  int modifiers,
  ffi.Pointer<ffi.Size> out_size,
);

/// Unified animation tick for all core-managed animation flags.
/// Platform schedules the next call from animation_flags and next_animation_delay_ms.
/// Returns the same EditorActionResult binary layout as editor_handle_gesture_event.
/// When animation_flags becomes zero in the returned payload, stop scheduling.
/// @return EditorActionResult binary payload
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_tick_animations(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Handle keyboard event (optional default key mapping; platform layer can bypass this API and call atomic operation APIs directly)
/// @param key_code Key code (KeyCode enum value)
/// @param text Input text (UTF8; pass for normal character input, pass NULL for special keys)
/// @param modifiers Modifier key flags(SHIFT=1, CTRL=2, ALT=4, META=8)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Uint16,
    ffi.Pointer<ffi.Char>,
    ffi.Uint8,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_handle_key_event(
  int editor_handle,
  int key_code,
  ffi.Pointer<ffi.Char> text,
  int modifiers,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set custom key map from binary payload.
/// @param data SetKeyMapPayload binary payload encoded by CoreProtocol
/// List<KeyBinding> bindings
/// KeyBinding is KeyChord first, KeyChord second, u32 command
/// KeyChord is u8 modifiers followed by u16 key_code
/// second.key_code == 0 means a single-chord binding
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_keymap(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Insert text at cursor position (replace selected text if selection exists)
/// @param text UTF8 text to insert
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_insert_text(
  int editor_handle,
  ffi.Pointer<ffi.Char> text,
  ffi.Pointer<ffi.Size> out_size,
);

/// Replace text in the specified range (atomic operation for precise replacements such as textEdit)
/// @param start_line start line of replacement range(0-based)
/// @param start_column Start column of replacement range (0-based)
/// @param end_line end line of replacement range(0-based)
/// @param end_column End column of replacement range (0-based)
/// @param text Replacement UTF8 text
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_replace_text(
  int editor_handle,
  int start_line,
  int start_column,
  int end_line,
  int end_column,
  ffi.Pointer<ffi.Char> text,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete text in the specified range
/// @param start_line start line of deletion range(0-based)
/// @param start_column Start column of deletion range (0-based)
/// @param end_line end line of deletion range(0-based)
/// @param end_column End column of deletion range (0-based)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_delete_text(
  int editor_handle,
  int start_line,
  int start_column,
  int end_line,
  int end_column,
  ffi.Pointer<ffi.Size> out_size,
);

/// Apply multiple text edits as one undoable operation.
/// @param data ApplyTextEditsPayload binary payload encoded by CoreProtocol
/// List<TextEdit> edits
/// TextEdit is TextRange range followed by U8String new_text
/// edits[0] is the primary edit and determines the final cursor position
/// @param size payload byte length
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_apply_text_edits(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete one character before cursor (Backspace behavior); delete selection if present
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_backspace(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete one character after cursor (Delete behavior); delete selection if present
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_delete_forward(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move current line (or lines covered by selection) up by one line
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_move_line_up(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move current line (or lines covered by selection) down by one line
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_move_line_down(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Copy current line (or lines covered by selection) upward
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_copy_line_up(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Copy current line (or lines covered by selection) downward
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_copy_line_down(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Delete current line (or all lines covered by selection)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_delete_line(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Insert empty line above current line
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_insert_line_above(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Insert empty line below current line
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_insert_line_below(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Undo last edit operation
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_undo(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Redo last undone operation
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_redo(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Whether undo is available
/// @return 1=yes, 0=no
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_can_undo(int editor_handle);

/// Whether redo is available
/// @return 1=yes, 0=no
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_can_redo(int editor_handle);

/// Search document text.
/// @param data SearchRequest binary payload encoded by CoreProtocol
/// SearchRequest is U8String pattern followed by SearchOptions options
/// SearchOptions is bool case_sensitive, bool whole_word, bool use_regex, bool wrap_around, u32 max_matches
/// @param size payload byte length
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_search(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move to the next search match.
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_find_next_search_match(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move to the previous search match.
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_find_previous_search_match(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Replace the current search match.
/// @param data U8String replacement payload: u32 byte length followed by UTF-8 bytes
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_replace_current_search_match(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Replace all current search matches.
/// @param data U8String replacement payload: u32 byte length followed by UTF-8 bytes
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_replace_all_search_matches(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear active search state, rendered highlights, and the current search-owned selection.
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_search(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get the latest search state.
/// @return SearchState binary payload encoded by CoreProtocol
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_get_search_state(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set cursor position
/// @param line Line number(0-based)
/// @param column Column number (0-based)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_cursor_position(
  int editor_handle,
  int line,
  int column,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get cursor position
/// @param out_line Output: line number
/// @param out_column Output: column number
@ffi.Native<
  ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Size>, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external void editor_get_cursor_position(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_line,
  ffi.Pointer<ffi.Size> out_column,
);

/// Select all
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_select_all(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set selection range
/// @param start_line selection start line(0-based)
/// @param start_column selection start column (0-based)
/// @param end_line selection end line(0-based)
/// @param end_column selection end column (0-based)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_selection(
  int editor_handle,
  int start_line,
  int start_column,
  int end_line,
  int end_column,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get current selection range (two cursor positions)
/// @param out_start_line Output: selection start line
/// @param out_start_column Output: selection start column
/// @param out_end_line Output: selection end line
/// @param out_end_column Output: selection end column
/// @return 1=has selection, 0=no selection
@ffi.Native<
  ffi.Int Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external int editor_get_selection(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_start_line,
  ffi.Pointer<ffi.Size> out_start_column,
  ffi.Pointer<ffi.Size> out_end_line,
  ffi.Pointer<ffi.Size> out_end_column,
);

/// Get selected text
/// @return Selected text (UTF8)
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> editor_get_selected_text(int editor_handle);

/// Get text range of word at cursor (scan continuous word chars to the left)
/// @param out_start_line Output: start line
/// @param out_start_column Output: start column
/// @param out_end_line Output: end line
/// @param out_end_column Output: end column
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external void editor_get_word_range_at_cursor(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_start_line,
  ffi.Pointer<ffi.Size> out_start_column,
  ffi.Pointer<ffi.Size> out_end_line,
  ffi.Pointer<ffi.Size> out_end_column,
);

/// Get text content of word at cursor
/// @return Word text (UTF8); returns empty string when cursor is not on a word
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> editor_get_word_at_cursor(int editor_handle);

/// Move cursor left
/// @param extend_selection Whether to extend selection (Shift behavior)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_move_cursor_left(
  int editor_handle,
  int extend_selection,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move cursor right
/// @param extend_selection Whether to extend selection
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_move_cursor_right(
  int editor_handle,
  int extend_selection,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move cursor up
/// @param extend_selection Whether to extend selection
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_move_cursor_up(
  int editor_handle,
  int extend_selection,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move cursor down
/// @param extend_selection Whether to extend selection
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_move_cursor_down(
  int editor_handle,
  int extend_selection,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move cursor to line start
/// @param extend_selection Whether to extend selection
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_move_cursor_to_line_start(
  int editor_handle,
  int extend_selection,
  ffi.Pointer<ffi.Size> out_size,
);

/// Move cursor to line end
/// @param extend_selection Whether to extend selection
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_move_cursor_to_line_end(
  int editor_handle,
  int extend_selection,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set read-only mode
/// @param read_only 1=read-only, 0=editable
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_read_only(
  int editor_handle,
  int read_only,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get whether read-only mode is active
/// @return 1=read-only, 0=editable
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_is_read_only(int editor_handle);

/// Set auto indent mode
/// @param mode 0=NONE(no auto indent),1=KEEP_INDENT(keep previous line indent)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_auto_indent_mode(
  int editor_handle,
  int mode,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get current auto indent mode
/// @return 0=NONE, 1=KEEP_INDENT
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_get_auto_indent_mode(int editor_handle);

/// Set backspace unindent behavior
/// @param enabled 1=enabled, 0=disabled
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_backspace_unindent(
  int editor_handle,
  int enabled,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set whether Tab inserts spaces up to the next tab stop instead of a literal '\t'
/// @param enabled 1=insert spaces, 0=insert '\t'
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_insert_spaces(
  int editor_handle,
  int enabled,
  ffi.Pointer<ffi.Size> out_size,
);

/// Scroll to specified line
/// @param line Line number(0-based)
/// @param behavior Scroll behavior(0=GOTO_TOP, 1=GOTO_CENTER, 2=GOTO_BOTTOM)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Uint8,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_scroll_to_line(
  int editor_handle,
  int line,
  int behavior,
  ffi.Pointer<ffi.Size> out_size,
);

/// Go to specified line and column (scroll + cursor positioning)
/// @param line Line number(0-based)
/// @param column Column number (0-based)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_goto_position(
  int editor_handle,
  int line,
  int column,
  ffi.Pointer<ffi.Size> out_size,
);

/// Adjust scroll offset just enough to keep current cursor visible in viewport
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_ensure_cursor_visible(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Manually set scroll position (automatically clamped to valid range)
/// @param scroll_x Horizontal scroll offset
/// @param scroll_y Vertical scroll offset
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Float,
    ffi.Float,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_scroll(
  int editor_handle,
  double scroll_x,
  double scroll_y,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get scrollbar metrics
/// @return ScrollMetrics binary payload encoded by CoreProtocol. Caller owns returned buffer and must free it with free_binary_data.
/// Wire layout:
/// f32 scale
/// f32 scroll_x
/// f32 scroll_y
/// f32 max_scroll_x
/// f32 max_scroll_y
/// Size content_size
/// Size viewport_size
/// f32 text_area_x
/// f32 text_area_width
/// bool_i32 can_scroll_x
/// bool_i32 can_scroll_y
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_get_scroll_metrics(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get screen coordinate rect for any text position (for floating panel positioning)
/// @param line Line number(0-based)
/// @param column Column number (0-based)
/// @param out_x Output: x coordinate in viewport
/// @param out_y Output: y coordinate in viewport (line top)
/// @param out_height Output: line height
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
  )
>(assetId: _sweeteditorAssetId)
external void editor_get_position_rect(
  int editor_handle,
  int line,
  int column,
  ffi.Pointer<ffi.Float> out_x,
  ffi.Pointer<ffi.Float> out_y,
  ffi.Pointer<ffi.Float> out_height,
);

/// Get screen coordinate rect at current cursor position (shortcut)
/// @param out_x Output: x coordinate in viewport
/// @param out_y Output: y coordinate in viewport (line top)
/// @param out_height Output: line height
@ffi.Native<
  ffi.Void Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
  )
>(assetId: _sweeteditorAssetId)
external void editor_get_cursor_rect(
  int editor_handle,
  ffi.Pointer<ffi.Float> out_x,
  ffi.Pointer<ffi.Float> out_y,
  ffi.Pointer<ffi.Float> out_height,
);

/// Register text style (color + background color + font style)
/// @param style_id Style ID
/// @param color Foreground color value (ARGB)
/// @param background_color Background color value (ARGB), 0 means transparent
/// @param font_style Font style (FontStyle enum value)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Uint32,
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_register_text_style(
  int editor_handle,
  int style_id,
  int color,
  int background_color,
  int font_style,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set style ranges for specified line and layer.
/// @param data SetLineSpansPayload binary payload encoded by CoreProtocol
/// u32 line
/// enum_i32 layer
/// List<StyleSpan> spans
/// StyleSpan is u32 column, u32 length, u32 style_id
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_spans(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set style ranges for multiple lines.
/// @param data SetBatchLineSpansPayload binary payload encoded by CoreProtocol
/// enum_i32 layer
/// u32 entry_count
/// Repeated entry is u32 line followed by List<StyleSpan> spans
/// StyleSpan is u32 column, u32 length, u32 style_id
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_spans(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Register text styles.
/// @param data RegisterBatchTextStylesPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 style_id followed by TextStyle style
/// TextStyle is i32 color, i32 background_color, i32 font_style
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_register_batch_text_styles(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all style ranges for specified line and layer
/// @param line Line number(0-based)
/// @param layer Highlight layer (0=SYNTAX, 1=SEMANTIC)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Uint8,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_clear_line_spans(
  int editor_handle,
  int line,
  int layer,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all highlight spans in specified layer
/// @param layer Highlight layer (0=SYNTAX, 1=SEMANTIC)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Uint8, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_clear_highlights_layer(
  int editor_handle,
  int layer,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set inlay hints for specified line.
/// @param data SetLineInlayHintsPayload binary payload encoded by CoreProtocol
/// u32 line
/// List<InlayHint> hints
/// InlayHint is enum_i32 type, u32 column, i32 int_value, U8String text
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_inlay_hints(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set inlay hints for multiple lines.
/// @param data SetBatchLineInlayHintsPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 line followed by List<InlayHint> hints
/// InlayHint is enum_i32 type, u32 column, i32 int_value, U8String text
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_inlay_hints(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set phantom texts for specified line.
/// @param data SetLinePhantomTextsPayload binary payload encoded by CoreProtocol
/// u32 line
/// List<PhantomText> phantoms
/// PhantomText is u32 column followed by U8String text
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_phantom_texts(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set phantom texts for multiple lines.
/// @param data SetBatchLinePhantomTextsPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 line followed by List<PhantomText> phantoms
/// PhantomText is u32 column followed by U8String text
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_phantom_texts(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set gutter icons for specified line.
/// @param data SetLineGutterIconsPayload binary payload encoded by CoreProtocol
/// u32 line
/// List<GutterIcon> icons
/// GutterIcon is i32 icon_id
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_gutter_icons(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set gutter icons for multiple lines.
/// @param data SetBatchLineGutterIconsPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 line followed by List<GutterIcon> icons
/// GutterIcon is i32 icon_id
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_gutter_icons(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set max gutter icon count (affects reserved gutter width)
/// @param count Max icon count (0=no reserved space)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Uint32, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_max_gutter_icons(
  int editor_handle,
  int count,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all gutter icons
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_gutter_icons(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set CodeLens items for specified line.
/// @param data SetLineCodeLensPayload binary payload encoded by CoreProtocol
/// u32 line
/// List<CodeLensItem> items
/// CodeLensItem is i32 column, i32 command_id, U8String text
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_codelens(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set CodeLens items for multiple lines.
/// @param data SetBatchLineCodeLensPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 line followed by List<CodeLensItem> items
/// CodeLensItem is i32 column, i32 command_id, U8String text
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_codelens(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all CodeLens items
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_codelens(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set link ranges for specified line.
/// @param data SetLineLinksPayload binary payload encoded by CoreProtocol
/// u32 line
/// List<LinkSpan> links
/// LinkSpan is u32 column, u32 length, U8String target
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_links(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set link ranges for multiple lines.
/// @param data SetBatchLineLinksPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 line followed by List<LinkSpan> links
/// LinkSpan is u32 column, u32 length, U8String target
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_links(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all link ranges
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_links(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Resolve link target by line and column inside that link
/// @return UTF8 target string; caller owns returned buffer and must free it with free_u8_string.
/// Returns an empty string when no link matches the requested position.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Size, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Char> editor_get_link_target_at(
  int editor_handle,
  int line,
  int column,
);

/// Set diagnostic decoration ranges for specified line.
/// @param data SetLineDiagnosticsPayload binary payload encoded by CoreProtocol
/// u32 line
/// List<Diagnostic> diagnostics
/// Diagnostic is u32 column, u32 length, enum_i32 severity
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_diagnostics(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set diagnostic decoration ranges for multiple lines.
/// @param data SetBatchLineDiagnosticsPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 line followed by List<Diagnostic> diagnostics
/// Diagnostic is u32 column, u32 length, enum_i32 severity
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_diagnostics(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all diagnostic decorations
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_diagnostics(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set document highlight ranges for specified line.
/// @param data SetLineDocumentHighlightsPayload binary payload encoded by CoreProtocol
/// u32 line
/// List<DocumentHighlight> highlights
/// DocumentHighlight is u32 column, u32 length, enum_i32 kind
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_line_document_highlights(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set document highlight ranges for multiple lines.
/// @param data SetBatchLineDocumentHighlightsPayload binary payload encoded by CoreProtocol
/// u32 entry_count
/// Repeated entry is u32 line followed by List<DocumentHighlight> highlights
/// DocumentHighlight is u32 column, u32 length, enum_i32 kind
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_batch_line_document_highlights(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all document highlight ranges
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_document_highlights(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set indent guide list.
/// @param data SetIndentGuidesPayload binary payload encoded by CoreProtocol
/// List<IndentGuide> guides
/// IndentGuide is TextPosition start followed by TextPosition end
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_indent_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set bracket branch guide list.
/// @param data SetBracketGuidesPayload binary payload encoded by CoreProtocol
/// List<BracketGuide> guides
/// BracketGuide is TextPosition parent, TextPosition end, List<TextPosition> children
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_bracket_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set control-flow back-arrow guide list.
/// @param data SetFlowGuidesPayload binary payload encoded by CoreProtocol
/// List<FlowGuide> guides
/// FlowGuide is TextPosition start followed by TextPosition end
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_flow_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set horizontal separator guide list.
/// @param data SetSeparatorGuidesPayload binary payload encoded by CoreProtocol
/// List<SeparatorGuide> guides
/// SeparatorGuide is i32 line, enum_i32 style, i32 count, u32 text_end_column
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_separator_guides(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all code structure lines (indent guides, bracket guides, control-flow arrows, separators)
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_guides(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set bracket pair list (override default (){}[])
/// @param open_chars Open bracket char array (UTF-32)
/// @param close_chars Close bracket char array (UTF-32)
/// @param count Bracket pair count
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_bracket_pairs(
  int editor_handle,
  ffi.Pointer<ffi.Uint32> open_chars,
  ffi.Pointer<ffi.Uint32> close_chars,
  int count,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set auto-closing pair list (empty count = disable auto-closing)
/// @param open_chars Open char array (UTF-32)
/// @param close_chars Close char array (UTF-32)
/// @param count Pair count
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_auto_closing_pairs(
  int editor_handle,
  ffi.Pointer<ffi.Uint32> open_chars,
  ffi.Pointer<ffi.Uint32> close_chars,
  int count,
  ffi.Pointer<ffi.Size> out_size,
);

/// Externally set exact bracket match result (override built-in char scan)
/// @param open_line open bracket line number(0-based)
/// @param open_col open bracket column number (0-based)
/// @param close_line close bracket line number(0-based)
/// @param close_col close bracket column number (0-based)
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_matched_brackets(
  int editor_handle,
  int open_line,
  int open_col,
  int close_line,
  int close_col,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear externally set bracket match result (fall back to built-in char scan)
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_matched_brackets(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Set foldable region list.
/// @param data SetFoldRegionsPayload binary payload encoded by CoreProtocol
/// List<FoldRegion> regions
/// FoldRegion is u32 start_line, u32 end_line, bool_u8 collapsed
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_set_fold_regions(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Toggle fold state of specified line
/// @param line Line number(0-based)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Size, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_toggle_fold(
  int editor_handle,
  int line,
  ffi.Pointer<ffi.Size> out_size,
);

/// Fold region containing specified line
/// @param line Line number(0-based)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Size, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_fold_at(
  int editor_handle,
  int line,
  ffi.Pointer<ffi.Size> out_size,
);

/// Unfold region containing specified line
/// @param line Line number(0-based)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Size, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_unfold_at(
  int editor_handle,
  int line,
  ffi.Pointer<ffi.Size> out_size,
);

/// Fold all regions
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_fold_all(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Unfold all regions
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_unfold_all(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Check whether specified line is visible (not hidden by folding)
/// @param line Line number(0-based)
/// @return 1=visible, 0=hidden
@ffi.Native<ffi.Int Function(ffi.IntPtr, ffi.Size)>(
  assetId: _sweeteditorAssetId,
)
external int editor_is_line_visible(int editor_handle, int line);

/// Get visible logical line range from the most recent completed layout pass
/// @param out_start_line Output first visible logical line (inclusive)
/// @param out_end_line Output last visible logical line (inclusive), or -1 when empty
@ffi.Native<
  ffi.Void Function(ffi.IntPtr, ffi.Pointer<ffi.Int32>, ffi.Pointer<ffi.Int32>)
>(assetId: _sweeteditorAssetId)
external void editor_get_visible_line_range(
  int editor_handle,
  ffi.Pointer<ffi.Int32> out_start_line,
  ffi.Pointer<ffi.Int32> out_end_line,
);

/// Clear all highlight spans
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_highlights(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all inlay hints
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_inlay_hints(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all phantom texts
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_phantom_texts(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Clear all decoration data
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_clear_all_decorations(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Insert VSCode snippet template and enter linked editing mode (convenience API)
/// @param snippet_template VSCode snippet template (UTF8)
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_insert_snippet(
  int editor_handle,
  ffi.Pointer<ffi.Char> snippet_template,
  ffi.Pointer<ffi.Size> out_size,
);

/// Start linked editing mode with tab stop groups
/// @param data StartLinkedEditingPayload binary payload encoded by CoreProtocol
/// List<TabStopGroup> groups
/// TabStopGroup is u32 index, List<TextRange> ranges, U8String default_text
/// @param size payload byte length
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_start_linked_editing(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Whether linked editing mode is active
/// @return 1=yes, 0=no
@ffi.Native<ffi.Int Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external int editor_is_in_linked_editing(int editor_handle);

/// Linked editing: jump to next tab stop
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_linked_editing_next(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Linked editing: jump to previous tab stop
/// @return EditorActionResult binary payload, returns NULL on failure
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_linked_editing_prev(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Cancel linked editing mode
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Pointer<ffi.Size>)>(
  assetId: _sweeteditorAssetId,
)
external ffi.Pointer<ffi.Uint8> editor_cancel_linked_editing(
  int editor_handle,
  ffi.Pointer<ffi.Size> out_size,
);

/// Begin an IME session.
/// @param mutation_model ImeMutationModel enum value.
/// @return ImeState binary payload, returns NULL when editor handle is invalid.
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Int, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_ime_begin_session(
  int editor_handle,
  int mutation_model,
  ffi.Pointer<ffi.Size> out_size,
);

/// End an IME session using Finish semantics.
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Uint64, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_ime_end_session(
  int editor_handle,
  int session_id,
  ffi.Pointer<ffi.Size> out_size,
);

/// Apply one callback-scoped command batch.
/// @param data Binary payload encoded by CoreProtocol.
/// @param size Binary payload size in bytes.
/// @return EditorActionResult binary payload, returns NULL when editor handle is invalid or payload is invalid.
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_ime_apply_commands(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Apply one callback-scoped text update batch.
/// @param data Binary payload encoded by CoreProtocol.
/// @param size Binary payload size in bytes.
/// @return EditorActionResult binary payload, returns NULL when editor handle is invalid or payload is invalid.
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_ime_apply_text_updates(
  int editor_handle,
  ffi.Pointer<ffi.Uint8> data,
  int size,
  ffi.Pointer<ffi.Size> out_size,
);

/// Get the current state for an IME session.
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.Uint64, ffi.Pointer<ffi.Size>)
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_ime_get_state(
  int editor_handle,
  int session_id,
  ffi.Pointer<ffi.Size> out_size,
);

/// Read a slice from an IME text source.
@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.IntPtr,
    ffi.Uint64,
    ffi.Int,
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Size>,
  )
>(assetId: _sweeteditorAssetId)
external ffi.Pointer<ffi.Uint8> editor_ime_get_context(
  int editor_handle,
  int session_id,
  int source,
  int start_utf16,
  int length_utf16,
  ffi.Pointer<ffi.Size> out_size,
);

/// Free string memory allocated on C++ side
/// @param string_ptr String pointer
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_u16_string(int string_ptr);

/// Free UTF-8 string memory allocated on C++ side
/// @param string_ptr String pointer
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_u8_string(int string_ptr);

/// Free binary memory returned by C++ side
/// Applies to all APIs that return const uint8_t* + out_size.
/// Platform must call once after reading payload; NULL/0 can be safely ignored.
/// @param data_ptr Start address of binary payload
@ffi.Native<ffi.Void Function(ffi.IntPtr)>(assetId: _sweeteditorAssetId)
external void free_binary_data(int data_ptr);

/// Text measurement callback set, passed when creating EditorCore
final class text_measurer_t extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Float Function(ffi.Pointer<ffi.Uint16> text, ffi.Int32 font_style)
    >
  >
  measure_text_width;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Float Function(ffi.Pointer<ffi.Uint16> text)>
  >
  measure_inlay_hint_width;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Float Function(ffi.Int32 icon_id)>
  >
  measure_icon_width;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Float> arr, ffi.Size length)
    >
  >
  get_font_metrics;
}
