using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Shapes;
using Avalonia.Controls.Templates;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;
using Avalonia.Threading;
using SweetEditor;
using AvaControls = global::Avalonia.Controls;
using AvaInteractivity = global::Avalonia.Interactivity;
using AvaPath = global::Avalonia.Controls.Shapes.Path;
using AvaloniaRect = global::Avalonia.Rect;
using AvaloniaSize = global::Avalonia.Size;
using Button = global::Avalonia.Controls.Button;
using ToggleButton = global::Avalonia.Controls.Primitives.ToggleButton;

namespace SweetEditor.Avalonia.Demo;

internal sealed class MainView : UserControl
{
    [Flags]
    private enum DeferredChromeWork
    {
        None = 0,
        Summary = 1 << 0,
        SamplePickerPopup = 1 << 1,
    }

    private static readonly float[] ScalePresets = { 0.72f, 0.82f, 0.90f, 0.96f, 1.08f, 1.20f };
    private const double SamplePickerPopupMaxHeight = 320;
    private const string InlineSuggestionText =
        "\nvoid autoGenerated() {\n    std::cout << \"hello\" << std::endl;\n    return;\n}";

    private const string LinkedSnippet =
        "for (int ${1:i} = 0; ${1:i} < ${2:count}; ++${1:i})\n" +
        "{\n" +
        "    ${0:// body}\n" +
        "}";

    private readonly SweetEditorController controller = new();
    private SweetEditorControl? editor;
    private readonly TextBlock statusText = new();
    private readonly TextBlock summaryText = new();
    private readonly Grid layoutRoot = new();
    private readonly Border toolbarContainer = new();
    private readonly Border statusBar = new();
    private readonly Grid editorHost = new();
    private readonly Border samplePickerPopup = new();
    private readonly ScrollViewer samplePickerScrollViewer = new();
    private readonly StackPanel samplePickerItemsPanel = new();

    private readonly DemoSettings demoSettings;
    private readonly LoadingIndicator loadingIndicator = new();

    private readonly DemoDecorationProvider decorationProvider;
    private readonly DemoCompletionProvider completionProvider = new();
    private readonly DemoIconProvider iconProvider = new();
    private readonly DemoSelectionMenuItemProvider selectionMenuProvider;
    private readonly DemoNewLineActionProvider newLineActionProvider = new();
    private readonly EditorToolbarController toolbarController = new();
    private readonly SampleDocumentLoader sampleLoader;
    private readonly Border searchContainer = new();
    private readonly StackPanel replaceRow = new();
    private readonly TextBox searchTextBox = new();
    private readonly TextBox replaceTextBox = new();
    private readonly TextBlock searchCounterText = new();
    private readonly ToggleButton searchCaseButton = new();
    private readonly ToggleButton searchWholeWordButton = new();
    private readonly ToggleButton searchRegexButton = new();

    private DemoSampleFile? activeSample;
    private string currentLanguageId = "plaintext";
    private bool darkTheme = true;
    private bool perfOverlayEnabled;
    private bool useVsCodeKeyMap = true;
    private bool inlineSuggestionAutoEnabled = true;
    private bool allowPassiveInlineSuggestion;
    private bool foldCollapsed;
    private WrapMode wrapMode = WrapMode.NONE;
    private float currentScale = 1f;
    private DeferredChromeWork pendingChromeWork;
    private int pendingInlineSuggestionToken;
    private bool chromeRefreshScheduled;
    private bool editorInitializationScheduled;
    private bool demoInitialized;
    private string? lastSummaryValue;
    private SearchState searchState = new();

    public MainView()
    {
        demoSettings = DemoSettings.Load();

        decorationProvider = new DemoDecorationProvider(() => controller.GetDocument(), controller.RequestDecorationRefresh);
        selectionMenuProvider = new DemoSelectionMenuItemProvider(
            () => inlineSuggestionAutoEnabled,
            () => perfOverlayEnabled,
            () => useVsCodeKeyMap);
        sampleLoader = new SampleDocumentLoader(
            controller,
            decorationProvider,
            UpdateStatus,
            ApplyLanguageConfiguration,
            () => demoSettings.LastSampleFileName,
            PrepareForSampleLoad,
            toolbarController.SetSamplePickerEnabled);
        decorationProvider.HighlightBackendChanged += () =>
            Dispatcher.UIThread.Post(() => ScheduleChromeRefresh(DeferredChromeWork.Summary), DispatcherPriority.Background);

        ApplyPersistedSettings();
        BuildLayout();
        WireEvents();

        ScheduleEditorInitialization();
    }

    private void ApplyPersistedSettings()
    {
        darkTheme = demoSettings.DarkTheme;
        wrapMode = demoSettings.WrapMode;
        currentScale = demoSettings.CurrentScale > 0 ? demoSettings.CurrentScale : 1f;
        perfOverlayEnabled = demoSettings.PerfOverlayEnabled;
        useVsCodeKeyMap = demoSettings.UseVsCodeKeyMap;
        inlineSuggestionAutoEnabled = demoSettings.InlineSuggestionAutoEnabled;
    }

    private void SaveDemoSettings()
    {
        demoSettings.DarkTheme = darkTheme;
        demoSettings.WrapMode = wrapMode;
        demoSettings.CurrentScale = currentScale;
        demoSettings.PerfOverlayEnabled = perfOverlayEnabled;
        demoSettings.UseVsCodeKeyMap = useVsCodeKeyMap;
        demoSettings.InlineSuggestionAutoEnabled = inlineSuggestionAutoEnabled;
        demoSettings.LastSampleFileName = activeSample?.FileName;
        demoSettings.Save();
    }

    private void BuildLayout()
    {
        toolbarContainer.BorderThickness = new Thickness(0, 0, 0, 1);
        toolbarContainer.Padding = new Thickness(12, 8, 12, 8);
        toolbarContainer.Child = toolbarController.BuildView();
        BuildSearchPanel();

        samplePickerItemsPanel.Spacing = 4;
        samplePickerScrollViewer.Content = samplePickerItemsPanel;
        samplePickerScrollViewer.HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled;
        samplePickerScrollViewer.VerticalScrollBarVisibility = ScrollBarVisibility.Auto;

        samplePickerPopup.Child = samplePickerScrollViewer;
        samplePickerPopup.IsVisible = false;
        samplePickerPopup.Padding = new Thickness(6);
        samplePickerPopup.CornerRadius = new CornerRadius(8);
        samplePickerPopup.BorderThickness = new Thickness(1);
        samplePickerPopup.HorizontalAlignment = HorizontalAlignment.Left;
        samplePickerPopup.VerticalAlignment = VerticalAlignment.Top;
        samplePickerPopup.ZIndex = 70;

        loadingIndicator.IsLoading = false;
        loadingIndicator.LoadingText = "Loading sample...";
        loadingIndicator.ZIndex = 60;
        editorHost.Children.Add(loadingIndicator);

        statusText.Text = "Ready";
        statusText.FontSize = 12;
        statusText.TextTrimming = TextTrimming.CharacterEllipsis;
        summaryText.FontSize = 11;
        summaryText.TextTrimming = TextTrimming.CharacterEllipsis;
        summaryText.TextAlignment = TextAlignment.Right;
        summaryText.HorizontalAlignment = HorizontalAlignment.Right;

        Grid statusPanel = new()
        {
            ColumnDefinitions = new ColumnDefinitions("*,Auto"),
            Margin = new Thickness(12, 5, 12, 6),
            ColumnSpacing = 12,
            Children =
            {
                statusText,
            },
        };
        Grid.SetColumn(summaryText, 1);
        statusPanel.Children.Add(summaryText);

        statusBar.BorderThickness = new Thickness(0, 1, 0, 0);
        statusBar.Child = statusPanel;

        layoutRoot.RowDefinitions = new RowDefinitions("Auto,Auto,*,Auto");
        Grid.SetRow(toolbarContainer, 0);
        Grid.SetRow(searchContainer, 1);
        Grid.SetRow(editorHost, 2);
        Grid.SetRow(statusBar, 3);
        Grid.SetRowSpan(samplePickerPopup, 4);
        layoutRoot.Children.Add(toolbarContainer);
        layoutRoot.Children.Add(searchContainer);
        layoutRoot.Children.Add(editorHost);
        layoutRoot.Children.Add(statusBar);
        layoutRoot.Children.Add(samplePickerPopup);
        Content = layoutRoot;
    }

    private void BuildSearchPanel()
    {
        searchContainer.IsVisible = false;
        searchContainer.BorderThickness = new Thickness(0, 0, 0, 1);
        searchContainer.Padding = new Thickness(12, 6, 12, 8);

        searchTextBox.PlaceholderText = "Find";
        searchTextBox.MinWidth = 160;
        searchTextBox.Height = 32;
        searchTextBox.TextChanged += (_, _) => PerformSearch();
        searchTextBox.KeyDown += OnSearchTextBoxKeyDown;

        replaceTextBox.PlaceholderText = "Replace";
        replaceTextBox.MinWidth = 160;
        replaceTextBox.Height = 32;
        replaceTextBox.KeyDown += OnReplaceTextBoxKeyDown;

        ConfigureSearchToggle(searchCaseButton, "Aa", "Match case");
        ConfigureSearchToggle(searchWholeWordButton, "Word", "Whole word");
        ConfigureSearchToggle(searchRegexButton, ".*", "Use regular expression");
        searchCaseButton.IsCheckedChanged += (_, _) => PerformSearch();
        searchWholeWordButton.IsCheckedChanged += (_, _) => PerformSearch();
        searchRegexButton.IsCheckedChanged += (_, _) => PerformSearch();

        searchCounterText.Width = 54;
        searchCounterText.FontSize = 11.5;
        searchCounterText.VerticalAlignment = VerticalAlignment.Center;
        searchCounterText.TextAlignment = TextAlignment.Center;

        Grid searchRow = new()
        {
            ColumnDefinitions = new ColumnDefinitions("*,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto"),
            ColumnSpacing = 6,
        };
        searchRow.Children.Add(searchTextBox);
        AddSearchRowControl(searchRow, CreateSearchTextButton("\\n", "Insert newline token", () => InsertNewlineToken(searchTextBox)), 1);
        AddSearchRowControl(searchRow, searchCounterText, 2);
        AddSearchRowControl(searchRow, searchCaseButton, 3);
        AddSearchRowControl(searchRow, searchWholeWordButton, 4);
        AddSearchRowControl(searchRow, searchRegexButton, 5);
        AddSearchRowControl(searchRow, CreateSearchTextButton("↑", "Previous match", FindPreviousSearchMatch), 6);
        AddSearchRowControl(searchRow, CreateSearchTextButton("↓", "Next match", FindNextSearchMatch), 7);
        AddSearchRowControl(searchRow, CreateSearchTextButton("×", "Close search", CloseSearchPanel), 8);

        replaceRow.Orientation = Orientation.Horizontal;
        replaceRow.Spacing = 6;
        replaceRow.IsVisible = false;
        replaceRow.Children.Add(replaceTextBox);
        replaceRow.Children.Add(CreateSearchTextButton("\\n", "Insert newline token", () => InsertNewlineToken(replaceTextBox)));
        replaceRow.Children.Add(CreateSearchTextButton("Replace", "Replace current match", ReplaceCurrentSearchMatch, 64));
        replaceRow.Children.Add(CreateSearchTextButton("All", "Replace all matches", ReplaceAllSearchMatches, 44));

        StackPanel panel = new()
        {
            Spacing = 6,
            Children =
            {
                searchRow,
                replaceRow,
            },
        };
        searchContainer.Child = panel;
    }

    private static void AddSearchRowControl(Grid row, Control control, int column)
    {
        Grid.SetColumn(control, column);
        row.Children.Add(control);
    }

    private static Button CreateSearchTextButton(string text, string tooltip, Action action, double width = 30)
    {
        Button button = new()
        {
            Width = width,
            Height = 30,
            Padding = new Thickness(0),
            Content = new TextBlock
            {
                Text = text,
                FontSize = text.Length > 2 ? 11 : 13,
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center,
                TextAlignment = TextAlignment.Center,
            },
        };
        button.Click += (_, _) => action();
        ToolTip.SetTip(button, tooltip);
        return button;
    }

    private static void ConfigureSearchToggle(ToggleButton button, string text, string tooltip)
    {
        button.Width = text.Length > 2 ? 46 : 34;
        button.Height = 30;
        button.Padding = new Thickness(0);
        button.Content = new TextBlock
        {
            Text = text,
            FontSize = 11,
            HorizontalAlignment = HorizontalAlignment.Center,
            VerticalAlignment = VerticalAlignment.Center,
            TextAlignment = TextAlignment.Center,
        };
        ToolTip.SetTip(button, tooltip);
    }

    private void WireEvents()
    {
        toolbarController.SamplePickerButton.Click += (_, _) => ToggleSamplePickerPopup();
        toolbarController.UndoButton.Click += (_, _) => ExecuteAction(controller.Undo(), "Undo", "Nothing to undo");
        toolbarController.RedoButton.Click += (_, _) => ExecuteAction(controller.Redo(), "Redo", "Nothing to redo");
        toolbarController.SearchButton.Click += (_, _) => OpenSearchPanel(replaceMode: false);
        toolbarController.ReplaceButton.Click += (_, _) => OpenSearchPanel(replaceMode: true);
        toolbarController.ThemeButton.Click += (_, _) => ToggleTheme();
        toolbarController.WrapButton.Click += (_, _) => CycleWrapMode();
        toolbarController.ZoomOutButton.Click += (_, _) => StepScale(-1);
        toolbarController.ZoomInButton.Click += (_, _) => StepScale(1);
        toolbarController.PerfButton.Click += (_, _) => TogglePerfOverlay();
        toolbarController.HelpButton.Click += (_, _) => ShowKeyboardShortcutsDialog();

        controller.DocumentLoaded += (_, _) =>
        {
            foldCollapsed = false;
            allowPassiveInlineSuggestion = false;
            ClearSearchState();
            RefreshActionState();
            UpdateStatus(activeSample != null ? $"Loaded: {activeSample.FileName}" : "Document loaded");
            UpdateFeatureStrip();
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
        };

        controller.TextChanged += (_, e) =>
        {
            allowPassiveInlineSuggestion = true;
            CancelPendingInlineSuggestion();
            RefreshActionState();
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
        };

        controller.CursorChanged += (_, e) =>
        {
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
            MaybeShowInlineSuggestion(e.CursorPosition);
        };

        controller.SelectionChanged += (_, e) =>
        {
            CancelPendingInlineSuggestion();
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
        };

        controller.ScaleChanged += (_, e) =>
        {
            currentScale = e.Scale;
            RefreshActionState();
            UpdateStatus($"Scale: {e.Scale * 100:F0}%");
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
        };
        controller.LongPress += (_, e) =>
        {
            UpdateStatus($"Long press: {e.LocationInEditor.X:F0},{e.LocationInEditor.Y:F0}");
        };
        controller.DoubleTap += (_, e) =>
        {
            UpdateStatus($"Double tap: {e.LocationInEditor.X:F0},{e.LocationInEditor.Y:F0}");
        };
        controller.ContextMenu += (_, _) => UpdateStatus("Context menu requested");
        controller.GutterIconClick += (_, e) => UpdateStatus($"Gutter icon at line {e.Line}");
        controller.CodeLensClick += (_, e) =>
            UpdateStatus($"CodeLens {DescribeCodeLensCommand(e.CommandId)} at line {e.Line + 1}");
        controller.FoldToggle += (_, e) =>
        {
            foldCollapsed = !controller.IsLineVisible(e.Line + 1);
            UpdateStatus($"Fold toggled at line {e.Line} ({(e.IsGutter ? "gutter" : "placeholder")})");
            UpdateFeatureStrip();
        };
        controller.InlayHintClick += (_, e) =>
        {
            if (e.Type == InlayType.COLOR)
                UpdateStatus($"Color inlay clicked: 0x{e.IntValue:X8}");
            else if (e.Type == InlayType.ICON)
                UpdateStatus($"Icon inlay clicked: {e.IntValue}");
            else
                UpdateStatus($"Inlay clicked at {e.Line}:{e.Column}");
        };
        controller.CompletionItemsUpdated += items =>
        {
            Dispatcher.UIThread.Post(() =>
            {
                CancelPendingInlineSuggestion();
                ScheduleChromeRefresh(DeferredChromeWork.Summary);
            });
        };
        controller.CompletionDismissed += () => Dispatcher.UIThread.Post(() =>
        {
            MaybeShowInlineSuggestion(controller.GetCursorPosition());
            UpdateFeatureStrip();
        });
        controller.InlineSuggestionAccepted += suggestion =>
            {
                CancelPendingInlineSuggestion();
                UpdateStatus($"Ghost accepted at {suggestion.Line}:{suggestion.Column}");
                ScheduleChromeRefresh(DeferredChromeWork.Summary);
            };
        controller.InlineSuggestionDismissed += suggestion =>
        {
            CancelPendingInlineSuggestion();
            UpdateStatus($"Ghost dismissed at {suggestion.Line}:{suggestion.Column}");
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
        };

        AddHandler(InputElement.PointerPressedEvent, OnMainViewPointerPressed, AvaInteractivity.RoutingStrategies.Tunnel);
    }

    private void ScheduleEditorInitialization()
    {
        if (editorInitializationScheduled)
            return;

        editorInitializationScheduled = true;
        Dispatcher.UIThread.Post(() =>
        {
            editorInitializationScheduled = false;
            EnsureEditorCreated();
        }, DispatcherPriority.Background);
    }

    private void EnsureEditorCreated()
    {
        if (editor != null)
            return;

        SweetEditorControl createdEditor = new(controller)
        {
            HorizontalAlignment = HorizontalAlignment.Stretch,
            VerticalAlignment = VerticalAlignment.Stretch,
            Focusable = true,
        };
        if (OperatingSystem.IsAndroid())
            TextOptions.SetTextRenderingMode(createdEditor, TextRenderingMode.Alias);

        createdEditor.AddHandler(InputElement.KeyDownEvent, OnEditorKeyDown, AvaInteractivity.RoutingStrategies.Tunnel);
        editor = createdEditor;
        editorHost.Children.Insert(0, createdEditor);
        InitializeDemo();
    }

    private void InitializeDemo()
    {
        if (demoInitialized)
            return;

        demoInitialized = true;
        controller.SetEditorIconProvider(iconProvider);
        controller.AddDecorationProvider(decorationProvider);
        controller.AddCompletionProvider(completionProvider);
        controller.AddNewLineActionProvider(newLineActionProvider);
        controller.SetInlineSuggestionListener(new DemoInlineSuggestionListener(UpdateStatus));
        controller.SetSelectionMenuItemProvider(selectionMenuProvider);
        controller.SetSelectionMenuListener(new DemoSelectionMenuListener(HandleSelectionMenuAction));
        controller.SetKeyMap(CreateEditorKeyMap());

        EditorSettings? settings = controller.GetSettings();
        if (settings != null)
        {
            bool isAndroid = OperatingSystem.IsAndroid();
            settings.SetTypeface("monospace");
            settings.SetEditorTextSize(14.0f);
            currentScale = GetDefaultScale();
            settings.SetScale(currentScale);
            settings.SetContentStartPadding(isAndroid ? 2 : 6);
            settings.SetFoldArrowMode(FoldArrowMode.AUTO);
            settings.SetCurrentLineRenderMode(CurrentLineRenderMode.BORDER);
            settings.SetGutterSticky(!isAndroid);
            settings.SetMaxGutterIcons(1);
            settings.SetWrapMode(wrapMode);
            settings.SetAutoIndentMode(AutoIndentMode.KEEP_INDENT);
            settings.SetBackspaceUnindent(true);
            settings.SetDecorationScrollRefreshMinIntervalMs(isAndroid ? 80 : 64);
            settings.SetDecorationOverscanViewportMultiplier(isAndroid ? 0.20f : 0.12f);
        }

        ApplyTheme();
        sampleLoader.LoadInitialSamples(typeof(MainView).Assembly);
        SyncSamplePickerSelection();
        RefreshActionState();
        UpdateFeatureStrip();
        if (sampleLoader.SampleFiles.Count > 0)
            UpdateStatus($"Loaded {sampleLoader.SampleFiles.Count} demo samples");
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
    }

    private EditorKeyMap CreateEditorKeyMap()
    {
        EditorKeyMap keyMap = new(useVsCodeKeyMap ? EditorKeyMap.Vscode().Bindings : EditorKeyMap.DefaultKeyMap().Bindings);
        keyMap.RegisterCommand(
            new KeyBinding(new KeyChord(KeyModifier.CTRL, KeyCode.K), new KeyChord(KeyModifier.CTRL, KeyCode.D), 0),
            _ =>
            {
                controller.TriggerCompletion();
                UpdateStatus("Host keymap: completion triggered");
                return true;
            });
        return keyMap;
    }

    private void ApplyTheme()
    {
        ThemeVariant variant = darkTheme ? ThemeVariant.Dark : ThemeVariant.Light;
        Application.Current!.RequestedThemeVariant = variant;

        uint background = darkTheme ? 0xFF1B1E24 : 0xFFFAFBFD;
        uint surface = background;
        uint surfaceMuted = darkTheme ? 0xFF242A33 : 0xFFF1F4F8;
        uint border = darkTheme ? 0xFF313844 : 0xFFD7DEE8;
        uint foreground = darkTheme ? 0xFFD7DEE9 : 0xFF1F2937;
        uint secondary = darkTheme ? 0xFF7A8494 : 0xFF8A94A6;
        uint accent = darkTheme ? 0xFF4C9DFF : 0xFF0F7AD9;

        toolbarContainer.Background = CreateBrush(surface);
        toolbarContainer.BorderBrush = CreateBrush(border);
        Background = CreateBrush(background);
        statusBar.Background = CreateBrush(surface);
        statusBar.BorderBrush = CreateBrush(border);
        statusText.Foreground = CreateBrush(foreground);
        summaryText.Foreground = CreateBrush(secondary);
        searchContainer.Background = CreateBrush(surface);
        searchContainer.BorderBrush = CreateBrush(border);
        searchCounterText.Foreground = CreateBrush(secondary);
        searchTextBox.Foreground = CreateBrush(foreground);
        searchTextBox.Background = CreateBrush(surfaceMuted);
        searchTextBox.BorderBrush = CreateBrush(border);
        replaceTextBox.Foreground = CreateBrush(foreground);
        replaceTextBox.Background = CreateBrush(surfaceMuted);
        replaceTextBox.BorderBrush = CreateBrush(border);
        samplePickerPopup.Background = CreateBrush(darkTheme ? 0xFF1B1E24u : 0xFFFFFFFFu);
        samplePickerPopup.BorderBrush = CreateBrush(darkTheme ? 0xFF313844u : 0xFFD7DEE8u);

        toolbarController.SamplePickerChrome.Background = CreateBrush(surfaceMuted);
        toolbarController.SamplePickerChrome.BorderBrush = CreateBrush(border);
        toolbarController.SamplePickerChrome.BorderThickness = new Thickness(1);
        toolbarController.SamplePickerLabel.Foreground = CreateBrush(foreground);
        toolbarController.SamplePickerChevron.Stroke = CreateBrush(foreground);
        toolbarController.SetTheme(darkTheme);
        toolbarController.SetWrapMode(wrapMode);
        ApplyToolbarChrome(foreground, surfaceMuted, border, accent);

        controller.ApplyTheme(CreateEditorTheme(darkTheme));
        if (samplePickerPopup.IsVisible)
        {
            RebuildSamplePickerItems();
            ScheduleChromeRefresh(DeferredChromeWork.SamplePickerPopup);
        }
    }

    private static EditorTheme CreateEditorTheme(bool dark)
    {
        uint colorToken = dark ? 0xFF9CDCFEu : 0xFF0F766Eu;
        uint urlToken = dark ? 0xFF7DCFFFu : 0xFF005FB8u;
        return (dark ? EditorTheme.Dark() : EditorTheme.Light())
            .DefineTextStyle(DemoDecorationProvider.StyleColor, new TextStyle(unchecked((int)colorToken), 0))
            .DefineTextStyle(DemoDecorationProvider.StyleUrl, new TextStyle(unchecked((int)urlToken), 0));
    }

    private void PrepareForSampleLoad(DemoSampleFile sample)
    {
        activeSample = sample;
        demoSettings.LastSampleFileName = sample.FileName;
        demoSettings.Save();
        currentLanguageId = sample.LanguageId;
        foldCollapsed = false;
        allowPassiveInlineSuggestion = false;
        CancelPendingInlineSuggestion();
        controller.DismissCompletion();
        controller.DismissInlineSuggestion();
        HideSamplePickerPopup();
        controller.GetSettings()?.SetGutterSticky(!OperatingSystem.IsAndroid());

        loadingIndicator.IsLoading = true;
        loadingIndicator.LoadingText = $"Loading {sample.FileName}...";

        UpdateFeatureStrip();
    }

    private void ApplyLanguageConfiguration(string languageId)
    {
        currentLanguageId = languageId;
        controller.SetLanguageConfiguration(languageId.Equals("lua", StringComparison.OrdinalIgnoreCase)
            ? new LanguageConfiguration(
                "lua",
                brackets: new List<BracketPair> { new("(", ")"), new("{", "}"), new("[", "]") },
                autoClosingPairs: new List<BracketPair>
                {
                    new("(", ")"),
                    new("{", "}"),
                    new("[", "]"),
                    new("\"", "\""),
                    new("'", "'")
                },
                lineComment: "--",
                tabSize: 4,
                insertSpaces: true)
            : new LanguageConfiguration(
                languageId,
                brackets: new List<BracketPair> { new("(", ")"), new("{", "}"), new("[", "]") },
                autoClosingPairs: new List<BracketPair>
                {
                    new("(", ")"),
                    new("{", "}"),
                    new("[", "]"),
                    new("\"", "\""),
                    new("'", "'")
                },
                lineComment: "//",
                blockComment: new BlockComment("/*", "*/"),
                tabSize: 4,
                insertSpaces: true));

        UpdateFeatureStrip();
    }

    private void ToggleTheme()
    {
        darkTheme = !darkTheme;
        SaveDemoSettings();
        ApplyTheme();
        controller.RequestDecorationRefresh();
        UpdateFeatureStrip();
        UpdateStatus(darkTheme ? "Theme: dark" : "Theme: light");
    }

    private void CycleWrapMode()
    {
        WrapMode[] modes = Enum.GetValues<WrapMode>();
        int index = Array.IndexOf(modes, wrapMode);
        wrapMode = modes[(index + 1) % modes.Length];
        controller.GetSettings()?.SetWrapMode(wrapMode);
        toolbarController.SetWrapMode(wrapMode);
        SaveDemoSettings();
        UpdateFeatureStrip();
        UpdateStatus($"Wrap: {wrapMode}");
    }

    private void StepScale(int delta)
    {
        EditorSettings? settings = controller.GetSettings();
        if (settings == null)
            return;

        int nearestIndex = 0;
        float bestDistance = float.MaxValue;
        for (int i = 0; i < ScalePresets.Length; i++)
        {
            float distance = Math.Abs(ScalePresets[i] - currentScale);
            if (distance < bestDistance)
            {
                bestDistance = distance;
                nearestIndex = i;
            }
        }

        int nextIndex = Math.Clamp(nearestIndex + delta, 0, ScalePresets.Length - 1);
        float nextScale = ScalePresets[nextIndex];
        currentScale = nextScale;
        settings.SetScale(nextScale);
        SaveDemoSettings();
        RefreshActionState();
        UpdateStatus($"Scale: {nextScale * 100:F0}%");
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
    }

    private float GetDefaultScale() => OperatingSystem.IsAndroid() ? 0.90f : 1.0f;

    private void TogglePerfOverlay()
    {
        perfOverlayEnabled = !perfOverlayEnabled;
        controller.SetPerfOverlayEnabled(perfOverlayEnabled);
        SaveDemoSettings();
        UpdateFeatureStrip();
        UpdateStatus(perfOverlayEnabled ? "Perf overlay: ON" : "Perf overlay: OFF");
    }

    private void ToggleKeyMap()
    {
        useVsCodeKeyMap = !useVsCodeKeyMap;
        controller.SetKeyMap(CreateEditorKeyMap());
        SaveDemoSettings();
        UpdateFeatureStrip();
        UpdateStatus(useVsCodeKeyMap ? "Keymap: VS Code" : "Keymap: default");
    }

    private void TriggerCompletion()
    {
        CancelPendingInlineSuggestion();
        controller.TriggerCompletion();
        UpdateFeatureStrip();
        UpdateStatus("Completion requested");
    }

    private void ShowInlineSuggestionAtCursor()
    {
        CancelPendingInlineSuggestion();
        TextPosition cursor = controller.GetCursorPosition();
        controller.ShowInlineSuggestion(new InlineSuggestion(cursor.Line, cursor.Column, InlineSuggestionText));
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
        UpdateStatus($"Ghost text shown at {cursor.Line}:{cursor.Column}");
    }

    private void InsertSnippetAtCursor()
    {
        controller.InsertSnippet(LinkedSnippet);
        UpdateStatus("Snippet inserted; use Tab to walk linked edits");
    }

    private void FoldAll()
    {
        controller.FoldAll();
        foldCollapsed = true;
        UpdateFeatureStrip();
        UpdateStatus("Folded all visible regions");
    }

    private void UnfoldAll()
    {
        controller.UnfoldAll();
        foldCollapsed = false;
        UpdateFeatureStrip();
        UpdateStatus("Unfolded all regions");
    }

    private void SyncSamplePickerSelection()
    {
        string? selectedFileName = activeSample?.FileName
            ?? sampleLoader.SelectedSample?.FileName
            ?? sampleLoader.SampleFiles.FirstOrDefault()?.FileName;
        toolbarController.SetSamplePickerLabel(selectedFileName);
        RebuildSamplePickerItems();
        ScheduleChromeRefresh(DeferredChromeWork.SamplePickerPopup | DeferredChromeWork.Summary);
    }

    private void ToggleSamplePickerPopup()
    {
        if (samplePickerPopup.IsVisible)
        {
            HideSamplePickerPopup();
            return;
        }

        ShowSamplePickerPopup();
    }

    private void ShowSamplePickerPopup()
    {
        if (sampleLoader.SampleFiles.Count == 0 || !toolbarController.SamplePickerButton.IsEnabled)
            return;

        RebuildSamplePickerItems();
        samplePickerPopup.IsVisible = true;
        toolbarController.SetSamplePickerExpanded(true);
        ScheduleChromeRefresh(DeferredChromeWork.SamplePickerPopup);
    }

    private void HideSamplePickerPopup()
    {
        samplePickerPopup.IsVisible = false;
        toolbarController.SetSamplePickerExpanded(false);
    }

    private void RebuildSamplePickerItems()
    {
        samplePickerItemsPanel.Children.Clear();
        string? selectedFileName = activeSample?.FileName ?? sampleLoader.SelectedSample?.FileName;
        foreach (DemoSampleFile sample in sampleLoader.SampleFiles)
        {
            bool isSelected = string.Equals(sample.FileName, selectedFileName, StringComparison.Ordinal);
            samplePickerItemsPanel.Children.Add(BuildSamplePickerItem(sample, isSelected));
        }
    }

    private Control BuildSamplePickerItem(DemoSampleFile sample, bool isSelected)
    {
        uint foreground = darkTheme ? 0xFFD7DEE9u : 0xFF1F2937u;
        uint secondary = darkTheme ? 0xFF7A8494u : 0xFF8A94A6u;
        uint background = isSelected
            ? (darkTheme ? 0xFF2A3A52u : 0xFFE4F0FFu)
            : (darkTheme ? 0xFF1B1E24u : 0xFFFFFFFFu);
        uint border = isSelected
            ? (darkTheme ? 0xFF4C9DFFu : 0xFF0F7AD9u)
            : (darkTheme ? 0xFF313844u : 0xFFD7DEE8u);
        string detail = sample.LanguageId;

        Grid row = new()
        {
            ColumnDefinitions = new ColumnDefinitions("*,Auto"),
            ColumnSpacing = 8,
            HorizontalAlignment = HorizontalAlignment.Stretch,
            VerticalAlignment = VerticalAlignment.Center,
        };
        row.Children.Add(new TextBlock
        {
            Text = sample.FileName,
            FontSize = 12.5,
            FontWeight = isSelected ? FontWeight.SemiBold : FontWeight.Medium,
            Foreground = CreateBrush(foreground),
            TextTrimming = TextTrimming.CharacterEllipsis,
            VerticalAlignment = VerticalAlignment.Center,
        });

        TextBlock detailText = new()
        {
            Text = detail,
            FontSize = 10.5,
            Foreground = CreateBrush(secondary),
            VerticalAlignment = VerticalAlignment.Center,
            TextAlignment = TextAlignment.Right,
        };
        Grid.SetColumn(detailText, 1);
        row.Children.Add(detailText);

        Border chrome = new()
        {
            Padding = new Thickness(10, 8),
            CornerRadius = new CornerRadius(10),
            Background = CreateBrush(background),
            BorderBrush = CreateBrush(border),
            BorderThickness = new Thickness(1),
            Child = row,
        };

        Button button = new()
        {
            Background = Brushes.Transparent,
            BorderBrush = Brushes.Transparent,
            BorderThickness = new Thickness(0),
            Padding = new Thickness(0),
            HorizontalAlignment = HorizontalAlignment.Stretch,
            HorizontalContentAlignment = HorizontalAlignment.Stretch,
            Content = chrome,
        };
        button.Click += (_, _) =>
        {
            HideSamplePickerPopup();
            if (!string.Equals(activeSample?.FileName, sample.FileName, StringComparison.Ordinal))
                _ = sampleLoader.LoadSampleAsync(sample);
        };
        return button;
    }

    private void RepositionSamplePickerPopup()
    {
        if (!samplePickerPopup.IsVisible)
            return;

        if (!TryGetControlBoundsInLayoutRoot(toolbarController.SamplePickerButton, out AvaloniaRect buttonBounds))
            return;

        double margin = 8;
        double rootWidth = layoutRoot.Bounds.Width;
        double rootHeight = layoutRoot.Bounds.Height;
        if (rootWidth <= 0 || rootHeight <= 0)
            return;

        double maxWidth = Math.Max(160, rootWidth - margin * 2);
        double width = Math.Clamp(Math.Max(buttonBounds.Width, 220), 160, maxWidth);
        samplePickerPopup.Width = width;
        samplePickerPopup.MaxHeight = Math.Max(120, Math.Min(SamplePickerPopupMaxHeight, rootHeight - buttonBounds.Bottom - margin * 2));
        samplePickerPopup.Measure(new AvaloniaSize(width, double.PositiveInfinity));

        double x = Math.Clamp(buttonBounds.X, margin, Math.Max(margin, rootWidth - width - margin));
        double y = Math.Max(margin, buttonBounds.Bottom + 4);
        samplePickerPopup.Margin = new Thickness(x, y, 0, 0);
    }

    private bool TryGetControlBoundsInLayoutRoot(Control control, out AvaloniaRect bounds)
    {
        bounds = default;
        Point? origin = control.TranslatePoint(default, layoutRoot);
        if (!origin.HasValue)
            return false;

        bounds = new AvaloniaRect(origin.Value, control.Bounds.Size);
        return bounds.Width > 0 && bounds.Height > 0;
    }

    private void OnMainViewPointerPressed(object? sender, PointerPressedEventArgs e)
    {
        if (!samplePickerPopup.IsVisible)
            return;

        Point point = e.GetPosition(layoutRoot);
        bool insideButton = TryGetControlBoundsInLayoutRoot(toolbarController.SamplePickerButton, out AvaloniaRect buttonBounds) &&
                            buttonBounds.Contains(point);
        bool insidePopup = TryGetControlBoundsInLayoutRoot(samplePickerPopup, out AvaloniaRect popupBounds) &&
                           popupBounds.Contains(point);
        if (!insideButton && !insidePopup)
            HideSamplePickerPopup();
    }

    private void MaybeShowInlineSuggestion(TextPosition cursor)
    {
        CancelPendingInlineSuggestion();
        if (!allowPassiveInlineSuggestion || !inlineSuggestionAutoEnabled || controller.IsInlineSuggestionShowing())
            return;

        (bool hasSelection, _) = controller.GetSelection();
        if (hasSelection)
            return;

        Document? doc = controller.GetDocument();
        if (doc == null)
            return;

        string lineText = doc.GetLineText(cursor.Line) ?? string.Empty;
        if (lineText.Trim().Length == 0 || cursor.Column != lineText.Length)
            return;

        int token = ++pendingInlineSuggestionToken;
        DispatcherTimer.RunOnce(() =>
        {
            if (token != pendingInlineSuggestionToken || controller.IsInlineSuggestionShowing())
                return;

            controller.ShowInlineSuggestion(new InlineSuggestion(cursor.Line, cursor.Column, InlineSuggestionText));
            ScheduleChromeRefresh(DeferredChromeWork.Summary);
        }, TimeSpan.FromMilliseconds(OperatingSystem.IsAndroid() ? 1000 : 700));
    }

    private void ApplyToolbarChrome(uint foreground, uint surfaceMuted, uint border, uint accent)
    {
        foreach (Button button in toolbarController.ActionButtons)
        {
            button.Foreground = CreateBrush(foreground);
            button.Background = Brushes.Transparent;
            button.BorderBrush = Brushes.Transparent;

            if (button.Content is Border chrome)
            {
                bool active = ReferenceEquals(button, toolbarController.PerfButton) && perfOverlayEnabled;
                ApplyActionChrome(chrome, foreground, surfaceMuted, border, active ? accent : surfaceMuted, active ? 0xFFFFFFFFu : foreground);
            }
        }
    }

    private static void ApplyActionChrome(Border chrome, uint foreground, uint surfaceMuted, uint border, uint background, uint textColor)
    {
        chrome.Background = CreateBrush(background);
        chrome.BorderBrush = CreateBrush(border);
        chrome.BorderThickness = new Thickness(1);

        if (chrome.Child is AvaPath path)
        {
            path.Fill = CreateBrush(textColor);
            return;
        }

        if (chrome.Child is TextBlock label)
        {
            label.Foreground = CreateBrush(textColor);
            return;
        }

        if (chrome.Child is Grid grid)
        {
            foreach (Control child in grid.Children.OfType<Control>())
            {
                if (child is AvaPath iconPath)
                {
                    iconPath.Fill = CreateBrush(textColor);
                }
                else if (child is Border badge && badge.Child is TextBlock badgeText)
                {
                    badge.Background = CreateBrush(textColor);
                    badgeText.Foreground = CreateBrush(surfaceMuted);
                }
            }
        }
    }

    private void RefreshActionState()
    {
        bool canUndo = controller.CanUndo();
        bool canRedo = controller.CanRedo();
        toolbarController.UndoButton.IsEnabled = canUndo;
        toolbarController.UndoButton.Opacity = canUndo ? 1.0 : 0.42;
        toolbarController.RedoButton.IsEnabled = canRedo;
        toolbarController.RedoButton.Opacity = canRedo ? 1.0 : 0.42;

        float minScale = ScalePresets[0];
        float maxScale = ScalePresets[^1];
        bool canZoomOut = currentScale > minScale + 0.0001f;
        bool canZoomIn = currentScale < maxScale - 0.0001f;
        toolbarController.ZoomOutButton.IsEnabled = canZoomOut;
        toolbarController.ZoomOutButton.Opacity = canZoomOut ? 1.0 : 0.42;
        toolbarController.ZoomInButton.IsEnabled = canZoomIn;
        toolbarController.ZoomInButton.Opacity = canZoomIn ? 1.0 : 0.42;
    }

    private void ExecuteAction(bool succeeded, string success, string failed)
    {
        RefreshActionState();
        UpdateStatus(succeeded ? success : failed);
    }

    private void OpenSearchPanel(bool replaceMode)
    {
        searchContainer.IsVisible = true;
        replaceRow.IsVisible = replaceMode;
        searchTextBox.Focus();
        searchTextBox.SelectAll();
        PerformSearch();
    }

    private void CloseSearchPanel()
    {
        ClearSearchState();
        searchContainer.IsVisible = false;
        replaceRow.IsVisible = false;
        editor?.Focus();
        UpdateStatus("Search closed");
    }

    private void ClearSearchState()
    {
        controller.ClearSearch();
        searchState = new SearchState();
        RefreshSearchCounter();
    }

    private void PerformSearch()
    {
        if (!searchContainer.IsVisible)
            return;

        string pattern = DecodeNewlineTokens(searchTextBox.Text ?? string.Empty);
        if (pattern.Length == 0)
        {
            ClearSearchState();
            return;
        }

        controller.Search(new SearchRequest
        {
            Pattern = pattern,
            Options = new SearchOptions
            {
                CaseSensitive = searchCaseButton.IsChecked == true,
                WholeWord = searchWholeWordButton.IsChecked == true,
                UseRegex = searchRegexButton.IsChecked == true,
            },
        });
        RefreshSearchState();
        if (searchState.Status == SearchStatus.FAILED)
            UpdateStatus(string.IsNullOrEmpty(searchState.ErrorMessage) ? "Search failed" : searchState.ErrorMessage);
    }

    private void FindNextSearchMatch()
    {
        if (!searchContainer.IsVisible)
        {
            OpenSearchPanel(replaceMode: false);
            return;
        }

        controller.FindNextSearchMatch();
        RefreshSearchState();
    }

    private void FindPreviousSearchMatch()
    {
        if (!searchContainer.IsVisible)
        {
            OpenSearchPanel(replaceMode: false);
            return;
        }

        controller.FindPreviousSearchMatch();
        RefreshSearchState();
    }

    private void ReplaceCurrentSearchMatch()
    {
        if (!searchContainer.IsVisible)
            return;

        SearchState state = controller.GetSearchState();
        if (string.IsNullOrEmpty(searchTextBox.Text)
            || state.Status == SearchStatus.FAILED
            || !state.HasCurrentMatch)
            return;

        controller.ReplaceCurrentSearchMatch(DecodeNewlineTokens(replaceTextBox.Text ?? string.Empty));
        PerformSearch();
        UpdateStatus("Replace");
    }

    private void ReplaceAllSearchMatches()
    {
        if (!searchContainer.IsVisible)
            return;

        SearchState state = controller.GetSearchState();
        if (string.IsNullOrEmpty(searchTextBox.Text)
            || state.Status == SearchStatus.FAILED
            || state.MatchCount <= 0)
            return;

        int count = state.MatchCount;
        controller.ReplaceAllSearchMatches(DecodeNewlineTokens(replaceTextBox.Text ?? string.Empty));
        PerformSearch();
        UpdateStatus($"Replaced {count} matches");
    }

    private void RefreshSearchState()
    {
        searchState = controller.GetSearchState();
        RefreshSearchCounter();
    }

    private void RefreshSearchCounter()
    {
        string pattern = searchTextBox.Text ?? string.Empty;
        if (!searchContainer.IsVisible || pattern.Length == 0)
        {
            searchCounterText.Text = string.Empty;
            return;
        }

        if (searchState.Status == SearchStatus.FAILED)
        {
            searchCounterText.Text = "Error";
            return;
        }

        if (searchState.MatchCount <= 0)
        {
            searchCounterText.Text = "0/0";
            return;
        }

        int index = searchState.HasCurrentMatch ? searchState.CurrentIndex + 1 : 0;
        searchCounterText.Text = $"{index}/{searchState.MatchCount}";
    }

    private bool HandleSearchShortcut(KeyEventArgs e)
    {
        bool primary = e.KeyModifiers.HasFlag(KeyModifiers.Control) || e.KeyModifiers.HasFlag(KeyModifiers.Meta);
        if (primary && e.Key == Key.F)
        {
            OpenSearchPanel(replaceMode: false);
            e.Handled = true;
            return true;
        }

        if (primary && e.Key == Key.H)
        {
            OpenSearchPanel(replaceMode: true);
            e.Handled = true;
            return true;
        }

        if (searchContainer.IsVisible && e.Key == Key.Escape)
        {
            CloseSearchPanel();
            e.Handled = true;
            return true;
        }

        if (searchContainer.IsVisible && e.Key == Key.Enter && e.KeyModifiers.HasFlag(KeyModifiers.Shift))
        {
            FindPreviousSearchMatch();
            e.Handled = true;
            return true;
        }

        return false;
    }

    private void OnSearchTextBoxKeyDown(object? sender, KeyEventArgs e)
    {
        if (HandleSearchShortcut(e))
            return;

        if (e.Key == Key.Enter)
        {
            if (e.KeyModifiers.HasFlag(KeyModifiers.Shift))
                FindPreviousSearchMatch();
            else
                FindNextSearchMatch();
            e.Handled = true;
        }
    }

    private void OnReplaceTextBoxKeyDown(object? sender, KeyEventArgs e)
    {
        if (HandleSearchShortcut(e))
            return;

        if (e.Key == Key.Enter)
        {
            ReplaceCurrentSearchMatch();
            e.Handled = true;
        }
    }

    private void InsertNewlineToken(TextBox textBox)
    {
        string text = textBox.Text ?? string.Empty;
        int start = Math.Clamp(textBox.SelectionStart, 0, text.Length);
        int end = Math.Clamp(textBox.SelectionEnd, 0, text.Length);
        if (end < start)
            (start, end) = (end, start);

        textBox.Text = text.Remove(start, end - start).Insert(start, "\\n");
        textBox.SelectionStart = start + 2;
        textBox.SelectionEnd = start + 2;
        if (ReferenceEquals(textBox, searchTextBox))
            PerformSearch();
    }

    private static string DecodeNewlineTokens(string text)
    {
        StringBuilder builder = new(text.Length);
        for (int i = 0; i < text.Length; i++)
        {
            char ch = text[i];
            if (ch == '\\' && i + 1 < text.Length)
            {
                char next = text[i + 1];
                if (next == 'n')
                {
                    builder.Append('\n');
                    i++;
                    continue;
                }
                if (next == '\\')
                {
                    builder.Append('\\');
                    i++;
                    continue;
                }
            }
            builder.Append(ch);
        }
        return builder.ToString();
    }

    private void HandleSelectionMenuAction(string itemId)
    {
        switch (itemId)
        {
            case DemoSelectionMenuItemProvider.ActionTriggerCompletion:
                TriggerCompletion();
                break;
            case DemoSelectionMenuItemProvider.ActionAcceptInlineSuggestion:
                controller.AcceptInlineSuggestion();
                UpdateStatus("Ghost accepted");
                break;
            case DemoSelectionMenuItemProvider.ActionDismissInlineSuggestion:
                controller.DismissInlineSuggestion();
                UpdateStatus("Ghost dismissed");
                break;
            case DemoSelectionMenuItemProvider.ActionShowInlineSuggestion:
                ShowInlineSuggestionAtCursor();
                break;
            case DemoSelectionMenuItemProvider.ActionToggleInlineSuggestionAuto:
                inlineSuggestionAutoEnabled = !inlineSuggestionAutoEnabled;
                SaveDemoSettings();
                UpdateFeatureStrip();
                UpdateStatus(inlineSuggestionAutoEnabled ? "Auto ghost: ON" : "Auto ghost: OFF");
                break;
            case DemoSelectionMenuItemProvider.ActionInsertSnippet:
                InsertSnippetAtCursor();
                break;
            case DemoSelectionMenuItemProvider.ActionFoldAll:
                FoldAll();
                break;
            case DemoSelectionMenuItemProvider.ActionUnfoldAll:
                UnfoldAll();
                break;
            case DemoSelectionMenuItemProvider.ActionTogglePerfOverlay:
                TogglePerfOverlay();
                break;
            case DemoSelectionMenuItemProvider.ActionToggleKeyMap:
                ToggleKeyMap();
                break;
        }

        Dispatcher.UIThread.Post(() => ScheduleChromeRefresh(DeferredChromeWork.Summary), DispatcherPriority.Background);
    }

    private void OnEditorKeyDown(object? sender, KeyEventArgs e)
    {
        if (HandleSearchShortcut(e))
            return;

        if (samplePickerPopup.IsVisible && e.Key == Key.Escape)
        {
            HideSamplePickerPopup();
            e.Handled = true;
            return;
        }

        if (e.Key == Key.F1)
        {
            TriggerCompletion();
            e.Handled = true;
            return;
        }

        if (e.Key == Key.F2)
        {
            ShowInlineSuggestionAtCursor();
            e.Handled = true;
            return;
        }

        if (e.Key == Key.F3)
        {
            InsertSnippetAtCursor();
            e.Handled = true;
        }
    }

    private void UpdateFeatureStrip()
    {
        uint surfaceMuted = darkTheme ? 0xFF242A33u : 0xFFF1F4F8u;
        uint border = darkTheme ? 0xFF313844u : 0xFFD7DEE8u;
        uint foreground = darkTheme ? 0xFFD7DEE9u : 0xFF1F2937u;
        uint accent = darkTheme ? 0xFF4C9DFFu : 0xFF0F7AD9u;
        toolbarController.SetWrapMode(wrapMode);
        ApplyToolbarChrome(foreground, surfaceMuted, border, accent);
        ScheduleChromeRefresh(DeferredChromeWork.Summary);
    }

    private void CancelPendingInlineSuggestion()
    {
        pendingInlineSuggestionToken++;
    }

    private void UpdateSummary()
    {
        TextPosition cursor = controller.GetCursorPosition();
        string wrapLabel = wrapMode switch
        {
            WrapMode.WORD_BREAK => "W",
            WrapMode.CHAR_BREAK => "C",
            _ => "N",
        };
        string backendLabel = decorationProvider.HighlightBackendLabel.Contains("native", StringComparison.OrdinalIgnoreCase)
            ? "SweetLine"
            : decorationProvider.HighlightBackendLabel;
        string sampleName = activeSample == null ? "Sample" : System.IO.Path.GetFileNameWithoutExtension(activeSample.FileName);
        string perfLabel = perfOverlayEnabled ? " | FPS" : string.Empty;
        string nextValue = $"{sampleName} | {currentLanguageId} | {backendLabel} | {wrapLabel} | {currentScale * 100:F0}% | {cursor.Line + 1}:{cursor.Column + 1}{perfLabel}";
        if (string.Equals(lastSummaryValue, nextValue, StringComparison.Ordinal))
            return;

        lastSummaryValue = nextValue;
        summaryText.Text = nextValue;
    }

    private void ScheduleChromeRefresh(DeferredChromeWork work)
    {
        ScheduleChromeRefresh(work, DispatcherPriority.Background);
    }

    private void ScheduleChromeRefresh(DeferredChromeWork work, DispatcherPriority priority)
    {
        pendingChromeWork |= work;
        if (chromeRefreshScheduled)
            return;

        chromeRefreshScheduled = true;
        Dispatcher.UIThread.Post(ApplyScheduledChromeRefresh, priority);
    }

    private void ApplyScheduledChromeRefresh()
    {
        chromeRefreshScheduled = false;
        DeferredChromeWork work = pendingChromeWork;
        pendingChromeWork = DeferredChromeWork.None;

        if ((work & DeferredChromeWork.SamplePickerPopup) != 0 && samplePickerPopup.IsVisible)
            RepositionSamplePickerPopup();

        if ((work & DeferredChromeWork.Summary) != 0)
            UpdateSummary();
    }

    private void UpdateStatus(string message)
    {
        Dispatcher.UIThread.Post(() =>
        {
            statusText.Text = message;
            loadingIndicator.IsLoading = false;
        });
    }

    private static string DescribeCodeLensCommand(int commandId)
    {
        return commandId switch
        {
            DemoDecorationProvider.CodeLensRun => "▶ Run",
            DemoDecorationProvider.CodeLensDebug => "◎ Debug",
            _ => $"Command#{commandId}",
        };
    }

    private void ShowKeyboardShortcutsDialog()
    {
        KeyboardShortcutsDialog.Open((Window)this.VisualRoot!);
    }

    private static SolidColorBrush CreateBrush(uint argb) => new(Color.FromUInt32(argb));
}
